
# small = 8B models
MODELS_CATALOG = {
    "reasoning": [
        "gemini/gemini-2.0-flash-thinking-exp-01-21",
        "openrouter/google/gemini-2.0-flash-thinking-exp:free",
        "gemini/gemini-2.0-flash-thinking-exp-1219",
        "openrouter/google/gemini-2.0-flash-thinking-exp-1219:free",
        "openrouter/deepseek/deepseek-r1:free",
        ],
    "large": [
        "gemini/gemini-exp-1206",
        "openrouter/google/gemini-exp-1206:free",
        "gemini/gemini-exp-1121",
        "openrouter/google/gemini-exp-1121:free",
        "gemini/gemini-exp-1114",
        "openrouter/google/gemini-exp-1114:free",
        "gemini/gemini-1.5-pro-002",
        "gemini/gemini-1.5-pro-exp-0827",
        "openrouter/meta-llama/llama-3.1-405b-instruct:free",
        "gemini/gemini-1.5-pro-001",
        "mistral/mistral-large-2411",
        "mistral/mistral-large-2407",
        "mistral/mistral-large-2402",
        ],
    "medium": [
        "gemini/gemini-2.0-flash-exp",
        "openrouter/google/gemini-2.0-flash-exp:free",
        "gemini/gemini-1.5-flash-latest",
        "gemini/gemini-1.5-flash-002",
        "gemini/gemini-1.5-flash-exp-0827",
        "openrouter/google/gemini-flash-1.5-exp",
        "groq/llama-3.3-70b-versatile",
        "groq/llama-3.3-70b-specdec",
        "gemini/gemini-1.5-flash-001",
        "mistral/mistral-medium",
        ],
    "small": [
        "gemini/gemini-1.5-flash-8b-latest",
        "gemini/gemini-1.5-flash-8b-001",
        "gemini/gemini-1.5-flash-8b-exp-0924",
        "gemini/gemini-1.5-flash-8b-exp-0827",
        "openrouter/google/gemini-flash-1.5-8b-exp",
        "groq/gemma2-9b-it",
        "openrouter/google/gemma-2-9b-it:free",
        "mistal/ministral-8b-2410",
        "groq/llama-3.1-8b-instant",
        "openrouter/meta-llama/llama-3.1-8b-instruct:free",
        "groq/llama-3-8b-8192",
        "openrouter/meta-llama/llama-3-8b-instruct:free",
        ],
    "moderation": [
        "groq/llama-guard-3-8b",
        "mistral/mistral-moderation-2411",
        ],
        }